const PRODUCTS = {
  'vibro-brick-paver': {
    name: 'Vibro Brick Paver',
    category: 'Vibro Compaction',
    modelId: 'FTV-001',
    image: 'images/Vibro Brick Paver.png',
    colors: ['Grey', 'Red', 'Yellow', 'Black', 'Brown'],
    highlights: [
      { label: 'Thickness', value: '60 / 80', unit: 'mm' },
      { label: 'Colours',   value: '5',        unit: 'options' },
    ],
    shortDesc: 'Traditional brick-shaped vibro compaction paver with superior strength, perfect for walkways and industrial zones.',
    description: 'The Vibro Brick Paver is a classic brick-shaped paver manufactured using state-of-the-art Apollo Zenith German technology. Produced through vibro compaction, these pavers deliver superior strength and durability — suitable for residential walkways, commercial driveways and heavy-duty industrial zones.',
    specs: [
      ['Size',        '200 × 100 mm'],
      ['Thickness',   '60MM / 80MM'],
      ['Finish',      'Smooth / Textured'],
      ['Colours',     'Grey, Red, Yellow, Black, Brown'],
      ['Application', 'Walkways, Driveways, Industrial Zones'],
    ],
    features: [
      'Manufactured with Apollo Zenith German technology',
      'High compressive strength (≥ 35 N/mm²)',
      'Weather, frost and UV resistant',
      'Available in multiple colours',
      'Interlocking design for long-term stability',
      'Low maintenance — individual pavers replaceable',
    ],
    applications: [
      { label: 'Driveways',        desc: 'Residential and commercial vehicle entries.' },
      { label: 'Walkways',         desc: 'Pedestrian paths and public pavements.' },
      { label: 'Industrial Zones', desc: 'Factory floors and heavy-load aprons.' },
    ],
  },
  'vibro-unipaver': {
    name: 'Vibro Unipaver',
    category: 'Vibro Compaction',
    modelId: 'FTV-002',
    image: 'images/Vibro Unipaver.png',
    colors: ['Grey', 'Red', 'Yellow', 'Black', 'Brown'],
    highlights: [
      { label: 'Thickness', value: '80', unit: 'mm' },
      { label: 'Colours',   value: '5',        unit: 'options' },
    ],
    shortDesc: 'Versatile interlocking vibro unipaver suitable for pedestrian paths and vehicular areas alike.',
    description: 'The Vibro Unipaver is a versatile interlocking paver designed for both pedestrian and vehicular use. Its unique shape provides excellent interlock between pavers, offering a stable and attractive surface for a wide range of applications.',
    specs: [
      ['Type',        'Interlocking Unipaver'],
      ['Thickness',   '80MM'],
      ['Finish',      'Smooth'],
      ['Colours',     'Grey, Red, Yellow, Black, Brown'],
      ['Application', 'Pedestrian Paths, Parking, Plazas'],
    ],
    features: [
      'Unique interlocking design for maximum stability',
      'Suitable for both pedestrian and vehicular areas',
      'High load-bearing capacity',
      'Available in multiple colours',
      'Easy to lay and replace',
      'Apollo Zenith German technology',
    ],
    applications: [
      { label: 'Pedestrian Paths', desc: 'Footpaths, corridors and garden walkways.' },
      { label: 'Parking Areas',   desc: 'Open lots and covered parking decks.' },
      { label: 'Plazas',          desc: 'Commercial and civic open spaces.' },
    ],
  },
  'vibro-square-150': {
    name: 'Vibro Square Paver 150×150',
    category: 'Vibro Compaction',
    modelId: 'FTV-003',
    image: 'images/Vibro Square 150 x 150 x 60MM.png',
    colors: ['Grey', 'Red', 'Yellow', 'Black', 'Brown'],
    highlights: [
      { label: 'Thickness', value: '60',  unit: 'mm' },
      { label: 'Colours',   value: '5',   unit: 'options' },
    ],
    shortDesc: 'Compact 150×150mm square vibro compaction paver, great for walkways, courtyards and decorative areas.',
    description: 'The Vibro Square 150×150 paver offers a clean, modern square format ideal for walkways, courtyards and decorative flooring. Its compact size makes it perfect for detailed patterns and smaller spaces while retaining the full strength of vibro compaction technology.',
    specs: [
      ['Size',        '150 × 150 mm'],
      ['Thickness',   '60MM'],
      ['Finish',      'Smooth'],
      ['Colours',     'Grey, Red, Yellow, Black, Brown'],
      ['Application', 'Walkways, Courtyards, Decorative Areas'],
    ],
    features: [
      'Compact size for detailed pattern laying',
      'Clean square format for modern aesthetics',
      'High compressive strength',
      'Available in multiple colours',
      'Ideal for residential and commercial use',
      'Low maintenance surface',
    ],
    applications: [
      { label: 'Walkways',         desc: 'Garden paths and pedestrian corridors.' },
      { label: 'Courtyards',       desc: 'Residential and hospitality courtyards.' },
      { label: 'Decorative Areas', desc: 'Patios, pool surrounds and feature paving.' },
    ],
  },
  'vibro-square-200': {
    name: 'Vibro Square Paver 200×200',
    category: 'Vibro Compaction',
    modelId: 'FTV-004',
    image: 'images/Vibro Square 200 x 200 x 60MM.png',
    colors: ['Grey', 'Red', 'Yellow', 'Black', 'Brown'],
    highlights: [
      { label: 'Thickness', value: '60 / 80', unit: 'mm' },
      { label: 'Colours',   value: '5',        unit: 'options' },
    ],
    shortDesc: 'Large-format 200×200mm square vibro compaction paver for driveways, plazas and heavy-duty public spaces.',
    description: 'The Vibro Square 200×200 paver is a large-format paver engineered for high-traffic areas including driveways, public plazas and industrial spaces. Its greater surface area provides a bold visual impact while delivering outstanding structural performance.',
    specs: [
      ['Size',        '200 × 200 mm'],
      ['Thickness',   '60MM / 80MM'],
      ['Finish',      'Smooth / Textured'],
      ['Colours',     'Grey, Red, Yellow, Black, Brown'],
      ['Application', 'Driveways, Plazas, Public Spaces'],
    ],
    features: [
      'Large format for bold visual impact',
      'Suitable for heavy vehicular loads (80MM)',
      'High compressive strength',
      'Available in multiple colours',
      'Ideal for driveways and public spaces',
      'Apollo Zenith German technology',
    ],
    applications: [
      { label: 'Driveways',     desc: 'Residential and commercial vehicle entries.' },
      { label: 'Plazas',        desc: 'Large public and commercial open spaces.' },
      { label: 'Public Spaces', desc: 'Parks, civic areas and institutional grounds.' },
    ],
  },
  'rubbermould-square': {
    name: 'Rubbermould Square 150×150',
    category: 'Rubbermould',
    modelId: 'RMV-001',
    image: 'images/Rubbermould Square.png',
    colors: ['Grey', 'Red', 'Yellow', 'Black', 'Brown'],
    highlights: [
      { label: 'Thickness', value: '35', unit: 'mm' },
      { label: 'Colours',   value: '5',        unit: 'options' },
    ],
    shortDesc: 'Compact 150×150mm rubbermould square paver with a smooth finish — ideal for garden paths, courtyards and decorative flooring.',
    description: 'The Rubbermould Square 150×150 paver is cast using rubber moulds to produce a smooth, refined finish. Its compact size makes it ideal for detailed pattern laying in gardens, courtyards and residential pathways.',
    specs: [
      ['Size',        '150 × 150 mm'],
      ['Thickness',   '35MM'],
      ['Type',        'Rubbermould Cast'],
      ['Finish',      'Smooth'],
      ['Colours',     'Grey, Red, Yellow, Black, Brown'],
      ['Application', 'Gardens, Courtyards, Pedestrian Areas'],
    ],
    features: [
      'Smooth refined finish using rubber mould casting',
      'Compact size for detailed pattern laying',
      'Attractive appearance for decorative use',
      'Non-slip surface',
      'Lightweight and easy to handle',
      'Ideal for residential and commercial decorative use',
    ],
    applications: [
      { label: 'Gardens',          desc: 'Ornamental garden paths and borders.' },
      { label: 'Courtyards',       desc: 'Residential and hospitality courtyards.' },
      { label: 'Pedestrian Areas', desc: 'Footpaths and light-use walkways.' },
    ],
  },
  'rubbermould-square-200': {
    name: 'Rubbermould Square 200×200',
    category: 'Rubbermould',
    modelId: 'RMV-002',
    image: 'images/Rubbermould Square 200x200.png',
    colors: ['Grey', 'Red', 'Yellow', 'Black', 'Brown'],
    highlights: [
      { label: 'Thickness', value: '60', unit: 'mm' },
      { label: 'Colours',   value: '5',        unit: 'options' },
    ],
    shortDesc: 'Large-format 200×200mm rubbermould square paver with a smooth finish — ideal for driveways, plazas and open areas.',
    description: 'The Rubbermould Square 200×200 paver offers a larger format with the same smooth rubber mould finish. Its greater surface area delivers a bold visual impact, making it ideal for driveways, open plazas and commercial decorative flooring.',
    specs: [
      ['Size',        '200 × 200 mm'],
      ['Thickness',   '60MM'],
      ['Type',        'Rubbermould Cast'],
      ['Finish',      'Smooth'],
      ['Colours',     'Grey, Red, Yellow, Black, Brown'],
      ['Application', 'Driveways, Plazas, Commercial Areas'],
    ],
    features: [
      'Large format for bold visual impact',
      'Smooth refined finish using rubber mould casting',
      'Available in multiple colours',
      'Non-slip surface',
      'Suitable for driveways and open commercial areas',
      'Ideal for residential and commercial decorative use',
    ],
    applications: [
      { label: 'Driveways',        desc: 'Residential and commercial vehicle entries.' },
      { label: 'Plazas',           desc: 'Large public and commercial open spaces.' },
      { label: 'Commercial Areas', desc: 'Retail, hospitality and office forecourts.' },
    ],
  },
  'rubbermould-unipaver': {
    name: 'Rubbermould Unipaver',
    category: 'Rubbermould',
    modelId: 'RMV-003',
    image: 'images/Rubbermould Unipaver.png',
    colors: ['Grey', 'Red', 'Yellow', 'Black', 'Brown'],
    highlights: [
      { label: 'Thickness', value: '80', unit: 'mm' },
      { label: 'Colours',   value: '5',  unit: 'options' },
    ],
    shortDesc: 'Interlocking unipaver in rubbermould finish — combines interlocking strength with a refined aesthetic.',
    description: 'The Rubbermould Unipaver combines the classic interlocking unipaver shape with the smooth, attractive finish of rubber mould casting. It offers both structural performance and visual elegance for walkways, garden landscapes and decorative pavements.',
    specs: [
      ['Type',        'Interlocking Rubbermould'],
      ['Thickness',   '80MM'],
      ['Finish',      'Smooth'],
      ['Colours',     'Grey, Red, Yellow, Black, Brown'],
      ['Application', 'Walkways, Landscapes, Decorative'],
    ],
    features: [
      'Interlocking design with smooth rubbermould finish',
      'Combines strength with refined aesthetics',
      'Available in multiple colours',
      'Suitable for pedestrian walkways and landscapes',
      'Non-slip surface for safety',
      'Low maintenance',
    ],
    applications: [
      { label: 'Walkways',          desc: 'Garden and pedestrian pathways.' },
      { label: 'Landscapes',        desc: 'Parks, gardens and green spaces.' },
      { label: 'Decorative Paving', desc: 'Feature flooring and pool surrounds.' },
    ],
  },
  'chequered-tiles': {
    name: 'Chequered Tiles',
    category: 'Tiles',
    modelId: 'CHQ-001',
    image: null,
    icon: 'fa-grip',
    iconBg: 'linear-gradient(135deg,#f1c40f,#d4ac0d)',
    colors: ['Grey', 'Red', 'Yellow', 'Black', 'Brown'],
    highlights: [
      { label: 'Thickness', value: '25', unit: 'mm' },
      { label: 'Colours',   value: '5',        unit: 'options' },
    ],
    shortDesc: 'Classic anti-skid chequered pattern tiles for footpaths, commercial floors and public spaces.',
    description: 'Fortune Chequered Tiles feature a classic anti-skid chequered pattern ideal for footpaths, commercial floors and public areas. Available in a wide range of sizes and vibrant colours, these tiles are designed to enhance safety without compromising on aesthetics.',
    specs: [
      ['Size',        '300×300 mm / 400×400 mm'],
      ['Thickness',   '25MM'],
      ['Pattern',     'Chequered Anti-Skid'],
      ['Colours',     'Grey, Red, Yellow, Black, Brown'],
      ['Application', 'Footpaths, Commercial Floors, Public Areas'],
    ],
    features: [
      'Anti-skid chequered surface for safety',
      'Available in multiple sizes and colours',
      'High compressive strength',
      'Suitable for heavy foot traffic',
      'Weather and UV resistant',
      'Easy to clean and maintain',
    ],
    applications: [
      { label: 'Footpaths',         desc: 'Public and private pedestrian paths.' },
      { label: 'Commercial Floors', desc: 'Retail, office and factory entrances.' },
      { label: 'Public Areas',      desc: 'Bus stands, stations and civic spaces.' },
    ],
  },
  'hollow-block': {
    name: 'Hollow Block',
    category: 'Blocks',
    modelId: 'BLK-001',
    image: 'images/Hollow Blocks.png',
    highlights: [
      { label: 'Length',    value: '400', unit: 'mm' },
      { label: 'Height',    value: '200', unit: 'mm' },
      { label: 'Width',     value: '200', unit: 'mm' },
    ],
    shortDesc: 'Lightweight hollow cement blocks for boundary walls, compound structures and partitions.',
    description: 'Fortune Hollow Blocks are lightweight yet strong cement blocks widely used for boundary walls, compound fencing and non-load-bearing partition walls. Their hollow core reduces weight and improves thermal insulation while maintaining structural integrity.',
    specs: [
      ['Size',        '400×200×200 mm'],
      ['Type',        'Hollow Core'],
      ['Finish',      'Smooth'],
      ['Application', 'Boundary Walls, Partitions, Compound'],
    ],
    features: [
      'Lightweight hollow core design',
      'Reduces construction dead load',
      'Good thermal insulation properties',
      'Fast and easy to lay',
      'Available in standard sizes',
      'Cost-effective construction solution',
    ],
    applications: [
      { label: 'Boundary Walls', desc: 'Property perimeters and compound fencing.' },
      { label: 'Partitions',     desc: 'Internal non-load-bearing room dividers.' },
      { label: 'Compound Walls', desc: 'Industrial and residential compounds.' },
    ],
  },
  'solid-block': {
    name: 'Solid Block',
    category: 'Blocks',
    modelId: 'BLK-002',
    image: 'images/Solid Block.png',
    highlights: [
      { label: 'Length', value: '400', unit: 'mm' },
      { label: 'Height', value: '200', unit: 'mm' },
      { label: 'Width',  value: '200', unit: 'mm' },
    ],
    shortDesc: 'Dense solid cement blocks for load-bearing walls and industrial-grade construction.',
    description: 'Fortune Solid Blocks are dense, high-strength cement blocks designed for load-bearing walls and heavy-duty construction. Their solid construction provides superior compressive strength suitable for industrial, commercial and residential structural applications.',
    specs: [
      ['Size',        '400×200×200 mm'],
      ['Type',        'Solid Core'],
      ['Finish',      'Smooth'],
      ['Application', 'Load-bearing Walls, Industrial Construction'],
    ],
    features: [
      'High compressive strength (≥ 7.5 N/mm²)',
      'Dense solid construction for structural use',
      'Suitable for load-bearing applications',
      'Dimensionally accurate',
      'Durable and long-lasting',
      'Ideal for industrial and commercial projects',
    ],
    applications: [
      { label: 'Load-bearing Walls',      desc: 'Structural walls for multi-storey buildings.' },
      { label: 'Industrial Construction', desc: 'Factories, warehouses and commercial structures.' },
    ],
  },
  'kerbstone': {
    name: 'Kerbstone',
    category: 'Kerbs',
    modelId: 'KRB-001',
    image: 'images/Curb Stone.png',
    highlights: [
      { label: 'Sizes',   value: '3',       unit: 'options' },
      { label: 'Height',  value: '80–100',  unit: 'mm' },
      { label: 'Width',   value: '200–300', unit: 'mm' },
    ],
    shortDesc: 'Precast concrete kerb for road edges, garden borders and driveway demarcation.',
    description: 'Fortune Kerbstones are precast concrete kerbs used to define road edges, garden borders and driveway boundaries. They provide a clean, durable edge that withstands vehicular loads while enhancing the visual finish of any paving project.',
    specs: [
      ['Size (1)',     '200×300×80 mm'],
      ['Size (2)',     '300×200×80 mm'],
      ['Size (3)',     '300×300×100 mm'],
      ['Type',        'Precast Concrete'],
      ['Finish',      'Smooth'],
      ['Application', 'Roads, Driveways, Garden Borders'],
    ],
    features: [
      'Strong precast concrete construction',
      'Clean and precise edge definition',
      'Withstands vehicular loads',
      'Weather and abrasion resistant',
      'Easy to install',
      'Suitable for roads, driveways and landscapes',
    ],
    applications: [
      { label: 'Roads',          desc: 'Highway and road edge demarcation.' },
      { label: 'Driveways',      desc: 'Residential and commercial entry borders.' },
      { label: 'Garden Borders', desc: 'Landscape edge definition and planting beds.' },
    ],
  },
  'grass-pavers': {
    name: 'Grass Pavers',
    category: 'Specialty',
    modelId: 'GRN-001',
    image: 'images/Grass Pavers.png',
    highlights: [
      { label: 'Thickness',  value: '60', unit: 'mm' },
      { label: 'Open Area',  value: '30', unit: '%' },
    ],
    shortDesc: 'Open-cell grass pavers allowing vegetation to grow through — eco-friendly solution for green parking.',
    description: 'Fortune Grass Pavers are open-cell cement pavers that allow grass and vegetation to grow through the openings. They provide a permeable, eco-friendly surface ideal for green parking areas, garden paths and landscaping projects that require both load-bearing capacity and natural aesthetics.',
    specs: [
      ['Size',         '400×400×60 mm'],
      ['Type',         'Open-Cell'],
      ['Finish',       'Textured'],
      ['Permeability', 'High (open-cell design)'],
      ['Application',  'Green Parking, Gardens, Landscapes'],
    ],
    features: [
      'Open-cell design allows grass to grow through',
      'Reduces stormwater runoff',
      'Eco-friendly and sustainable',
      'High load-bearing capacity',
      'Natural aesthetic for green spaces',
      'Suitable for parking areas and garden paths',
    ],
    applications: [
      { label: 'Green Parking', desc: 'Eco-friendly vehicle parking areas.' },
      { label: 'Gardens',       desc: 'Ornamental and functional garden surfaces.' },
      { label: 'Landscapes',    desc: 'Parks, open spaces and green corridors.' },
    ],
  },
  'flyash-bricks': {
    name: 'Fly Ash Bricks',
    category: 'Eco',
    modelId: 'ECO-001',
    image: 'images/Flyash Bricks.png',
    highlights: [
      { label: 'Length',    value: '230', unit: 'mm' },
      { label: 'Height',    value: '70',  unit: 'mm' },
      { label: 'Width',     value: '110', unit: 'mm' },
    ],
    shortDesc: 'High-strength eco-friendly bricks made from fly ash with low water absorption and thermal insulation.',
    description: 'Fortune Fly Ash Bricks are manufactured using industrial fly ash, making them an eco-friendly alternative to traditional clay bricks. They offer superior strength, lower water absorption and better thermal insulation — contributing to greener, more energy-efficient construction.',
    specs: [
      ['Size',               '230×110×70 mm'],
      ['Type',               'Fly Ash Composite'],
      ['Thermal Insulation', 'Superior to clay bricks'],
      ['Application',        'Walls, Partitions, General Construction'],
    ],
    features: [
      'Made from recycled industrial fly ash',
      'Superior compressive strength',
      'Lower water absorption than clay bricks',
      'Better thermal insulation',
      'Reduces construction dead load',
      'Eco-friendly and sustainable choice',
    ],
    applications: [
      { label: 'Walls',                desc: 'External and internal building walls.' },
      { label: 'Partitions',           desc: 'Internal room dividers and partitions.' },
      { label: 'General Construction', desc: 'Residential and commercial buildings.' },
    ],
  },
};
